/**
 * Style Dictionary transforms — converts W3C tokens to platform-specific outputs.
 * Builds SD config programmatically per platform, returns generated file contents as strings.
 */

import type { W3CTokenFile } from "../types/tokens.js";
import type { SDPlatform, SDTransformResult } from "../types/tokens.js";

/**
 * Flatten W3C tokens to Style Dictionary input format (flat key-value with CTI path).
 */
function w3cToSDInput(tokens: W3CTokenFile, parentPath: string[] = []): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  for (const [key, val] of Object.entries(tokens)) {
    if (key.startsWith("$")) continue;

    if (isToken(val)) {
      result[key] = {
        value: val.$value,
        type: val.$type,
        ...(val.$description ? { comment: val.$description } : {}),
      };
    } else if (typeof val === "object" && val !== null) {
      result[key] = w3cToSDInput(val as W3CTokenFile, [...parentPath, key]);
    }
  }

  return result;
}

function isToken(val: unknown): val is { $value: unknown; $type?: string; $description?: string } {
  return typeof val === "object" && val !== null && "$value" in val;
}

/**
 * Flatten nested SD tokens to a flat array of { name, value, type, comment }
 */
interface FlatToken {
  name: string;
  value: string | number | boolean;
  type: string;
  comment?: string;
}

function flattenSD(obj: Record<string, unknown>, prefix: string[] = []): FlatToken[] {
  const tokens: FlatToken[] = [];

  for (const [key, val] of Object.entries(obj)) {
    const path = [...prefix, key];

    if (typeof val === "object" && val !== null && "value" in val) {
      const token = val as { value: unknown; type?: string; comment?: string };
      tokens.push({
        name: path.join("-"),
        value: token.value as string | number | boolean,
        type: token.type ?? "unknown",
        comment: token.comment,
      });
    } else if (typeof val === "object" && val !== null) {
      tokens.push(...flattenSD(val as Record<string, unknown>, path));
    }
  }

  return tokens;
}

/**
 * Generate CSS custom properties output.
 */
function generateCSS(tokens: FlatToken[]): string {
  const lines = [
    "/**",
    " * Design Tokens — CSS Custom Properties",
    " * Generated by DesignxCode MCP",
    " */",
    "",
    ":root {",
  ];

  for (const token of tokens) {
    if (token.comment) {
      lines.push(`  /* ${token.comment} */`);
    }
    lines.push(`  --${token.name}: ${token.value};`);
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

/**
 * Generate SCSS variables output.
 */
function generateSCSS(tokens: FlatToken[]): string {
  const lines = [
    "//",
    "// Design Tokens — SCSS Variables",
    "// Generated by DesignxCode MCP",
    "//",
    "",
  ];

  for (const token of tokens) {
    if (token.comment) {
      lines.push(`// ${token.comment}`);
    }
    lines.push(`$${token.name}: ${token.value};`);
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Generate Tailwind CSS config extension.
 */
function generateTailwind(tokens: FlatToken[]): string {
  const colors: Record<string, string> = {};
  const spacing: Record<string, string> = {};
  const other: Record<string, string> = {};

  for (const token of tokens) {
    const val = String(token.value);
    if (token.type === "color") {
      colors[token.name] = val;
    } else if (token.type === "dimension" || token.type === "number") {
      spacing[token.name] = val;
    } else {
      other[token.name] = val;
    }
  }

  const config: Record<string, unknown> = {};
  if (Object.keys(colors).length > 0) config.colors = colors;
  if (Object.keys(spacing).length > 0) config.spacing = spacing;
  if (Object.keys(other).length > 0) config.extend = other;

  const lines = [
    "/**",
    " * Design Tokens — Tailwind CSS Config Extension",
    " * Generated by DesignxCode MCP",
    " *",
    " * Usage: Spread into your tailwind.config.js theme.extend",
    " */",
    "",
    `module.exports = ${JSON.stringify({ theme: { extend: config } }, null, 2)};`,
    "",
  ];

  return lines.join("\n");
}

/**
 * Generate Swift UIColor/CGFloat constants.
 */
function generateSwift(tokens: FlatToken[]): string {
  const lines = [
    "//",
    "// Design Tokens — Swift Constants",
    "// Generated by DesignxCode MCP",
    "//",
    "",
    "import UIKit",
    "",
    "enum DesignTokens {",
  ];

  for (const token of tokens) {
    const swiftName = token.name
      .split("-")
      .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
      .join("");

    if (token.comment) {
      lines.push(`    /// ${token.comment}`);
    }

    if (token.type === "color" && typeof token.value === "string" && token.value.startsWith("#")) {
      const hex = token.value.replace("#", "");
      const r = parseInt(hex.substring(0, 2), 16) / 255;
      const g = parseInt(hex.substring(2, 4), 16) / 255;
      const b = parseInt(hex.substring(4, 6), 16) / 255;
      const a = hex.length > 6 ? parseInt(hex.substring(6, 8), 16) / 255 : 1;
      lines.push(
        `    static let ${swiftName} = UIColor(red: ${r.toFixed(3)}, green: ${g.toFixed(3)}, blue: ${b.toFixed(3)}, alpha: ${a.toFixed(3)})`
      );
    } else if (token.type === "number" || token.type === "dimension") {
      lines.push(`    static let ${swiftName}: CGFloat = ${token.value}`);
    } else {
      lines.push(`    static let ${swiftName} = "${token.value}"`);
    }
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

/**
 * Generate Kotlin Compose Color/Dp constants.
 */
function generateKotlin(tokens: FlatToken[]): string {
  const lines = [
    "//",
    "// Design Tokens — Kotlin Compose Constants",
    "// Generated by DesignxCode MCP",
    "//",
    "",
    "package designtokens",
    "",
    "import androidx.compose.ui.graphics.Color",
    "import androidx.compose.ui.unit.dp",
    "",
    "object DesignTokens {",
  ];

  for (const token of tokens) {
    const kotlinName = token.name
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("");

    if (token.comment) {
      lines.push(`    /** ${token.comment} */`);
    }

    if (token.type === "color" && typeof token.value === "string" && token.value.startsWith("#")) {
      const hex = token.value.replace("#", "");
      const fullHex = hex.length === 6 ? `FF${hex}` : hex.length === 8 ? `${hex.slice(6)}${hex.slice(0, 6)}` : hex;
      lines.push(`    val ${kotlinName} = Color(0x${fullHex.toUpperCase()})`);
    } else if (token.type === "dimension") {
      lines.push(`    val ${kotlinName} = ${token.value}.dp`);
    } else if (token.type === "number") {
      lines.push(`    val ${kotlinName} = ${token.value}f`);
    } else {
      lines.push(`    const val ${kotlinName} = "${token.value}"`);
    }
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

/**
 * Generate JSON output (raw flattened tokens).
 */
function generateJSON(tokens: FlatToken[]): string {
  const obj: Record<string, { value: string | number | boolean; type: string; comment?: string }> = {};
  for (const token of tokens) {
    obj[token.name] = {
      value: token.value,
      type: token.type,
      ...(token.comment ? { comment: token.comment } : {}),
    };
  }
  return JSON.stringify(obj, null, 2) + "\n";
}

const FILE_EXTENSIONS: Record<SDPlatform, string> = {
  css: "tokens.css",
  scss: "_tokens.scss",
  tailwind: "tokens.tailwind.cjs",
  swift: "DesignTokens.swift",
  kotlin: "DesignTokens.kt",
  json: "tokens.json",
};

const GENERATORS: Record<SDPlatform, (tokens: FlatToken[]) => string> = {
  css: generateCSS,
  scss: generateSCSS,
  tailwind: generateTailwind,
  swift: generateSwift,
  kotlin: generateKotlin,
  json: generateJSON,
};

/**
 * Transform W3C tokens into platform-specific code for the given platforms.
 * Returns generated file contents as strings (no disk writes).
 */
export function transformTokens(
  w3cTokens: W3CTokenFile,
  platforms: SDPlatform[]
): SDTransformResult[] {
  const sdInput = w3cToSDInput(w3cTokens);
  const flatTokens = flattenSD(sdInput);
  const results: SDTransformResult[] = [];

  for (const platform of platforms) {
    const generator = GENERATORS[platform];
    if (!generator) {
      throw new Error(`Unsupported platform: ${platform}`);
    }

    results.push({
      platform,
      fileName: FILE_EXTENSIONS[platform],
      content: generator(flatTokens),
    });
  }

  return results;
}
